server:
  port: 80
  servlet:
    context-path: /callback
spring:
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/test?serverTimezone=UTC&autoReconnect=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

  mvc:
    static-path-pattern: /**
  thymeleaf:
    cache: false
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/

